name: MuleSoft CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to CloudHub using client_credentials
      env:
        CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
        ENVIRONMENT: ${{ secrets.ANYPOINT_ENV }}
        APP_NAME: ${{ secrets.ANYPOINT_APP_NAME }}
      run: |
        echo "🔐 Getting access token using client_credentials..."
        TOKEN=$(curl -s -X POST https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET" \
          | jq -r '.access_token')

        if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
          echo "❌ Failed to get access token."
          exit 1
        fi

        echo "📦 Deploying application to CloudHub..."
        curl -X POST https://anypoint.mulesoft.com/cloudhub/api/v2/applications \
          -H "Authorization: Bearer $TOKEN" \
          -F "file=@target/newxml-1.0.0-SNAPSHOT-mule-application.jar" \
          -F "appInfo={\"domain\":\"$APP_NAME\",\"environment\":\"$ENVIRONMENT\",\"region\":\"us-east-1\"};type=application/json"